### ISSUE TITLE
Help flashing firmware

### ISSUE THREAD

**Issue by zejulio** [KooleControls/ESPTool#7] opened 2024-07-04 15:24 UTC
Hello,

I am sorry but dont know how to contact you other way.
I just want to flash the firmware.bin to my ESP32.
From what I see from the example app, I need to have the bootloader, firmware, storage and partition table for it to flash all, right?
Is there a way to do only firmware?

Thanks!

**Comment by vanBassum** [comment] 2024-07-05 08:54
You should be able to only write a single partition. 

I am currently away, so I can't help you right now. Im back in a couple of weeks, if the issue is not resolved by then, please send me a reminder

**Comment by zejulio** [comment] 2024-07-05 14:58
Hello,

It was missing some dependecies, I've updated with nuget and now it looks like it's working! Thanks!|

**Comment by vanBassum** [comment] 2024-07-22 08:50
I assume this means the issue is resolved, if it isn't please feel free to re open the issue.

**Closed as completed by vanBassum** 2024-07-22 08:50 UTC
